services:
  app:
    build: .
    ports:
      - "8081:8080"
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://dpg-ct52imjv2p9s738tl6hg-a.oregon-postgres.render.com:5432/realmart_tem4
      - DB_USERNAME=realmartuser
      - DB_PASSWORD=DsK4SOb2DSD2QrkDvRiBBBsEscAFLtGV



